#ifndef WINPR_CONFIG_H
#define WINPR_CONFIG_H

/* Include files */
#define WINPR_HAVE_FCNTL_H 1
#define WINPR_HAVE_UNISTD_H 1
#define WINPR_HAVE_INTTYPES_H 1
#define WINPR_HAVE_STDBOOL_H 1
/* #undef WINPR_HAVE_AIO_H */
/* #undef WINPR_HAVE_SYS_FILIO_H */
#define WINPR_HAVE_SYS_SELECT_H 1
/* #undef WINPR_HAVE_SYS_SOCKIO_H */
#define WINPR_HAVE_SYS_EVENTFD_H 1
#define WINPR_HAVE_SYS_TIMERFD_H 1
#define WINPR_HAVE_TM_GMTOFF 1
#define WINPR_HAVE_POLL_H 1
#define WINPR_HAVE_SYSLOG_H 1
/* #undef WINPR_HAVE_JOURNALD_H */
#define WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK 1
/* #undef WINPR_HAVE_EXECINFO_H */
#define WINPR_HAVE_GETLOGIN_R 1
#define WINPR_HAVE_GETPWUID_R 1
#define WINPR_HAVE_STRNDUP 1
/* #undef WINPR_HAVE_UNWIND_H */
#define WINPR_HAVE_SSIZE_T 1
/* #undef WINPR_HAVE_WIN_SSIZE_T */
/* #undef WINPR_WITH_PNG */

#define WINPR_HAVE_STRERROR_R 1

#define WITH_EVENTFD_READ_WRITE 1

/* #undef WITH_NATIVE_SSPI */
#define WITH_INTERNAL_RC4 1
#define WITH_INTERNAL_MD4 1
#define WITH_INTERNAL_MD5 1

/* #undef WITH_WINPR_JSON */

/* #undef WITH_DEBUG_NTLM */
/* #undef WITH_DEBUG_THREADS */
/* #undef WITH_DEBUG_EVENTS */
/* #undef WITH_DEBUG_MUTEX */

/* #undef WINPR_UTILS_IMAGE_WEBP */
/* #undef WINPR_UTILS_IMAGE_PNG */
/* #undef WINPR_UTILS_IMAGE_JPEG */

#endif /* WINPR_CONFIG_H */
